language: r
cache: packages
r_check_args: --as-cran

r:
  - release

r_packages:
  - pkgload
  - rsconnect

os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - devel

after_success:
  - Rscript -e 'covr::codecov()'
