language: r
cache: packages
r_check_args: --as-cran

r:
  - release

r_packages:
  - pkgload
  - rsconnect

os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: change

jobs:
  include:
    - stage: deploy
      script: Rscript dev/deploy.R
