language: r
cache: packages
r_check_args: --as-cran

r:
  - release

r_packages:
  - pkgload
  - rsconnect

os:
  - linux
  - osx

matrix:
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: script
  script: Rscript dev/deploy.R
