language: r
cache: packages
r_check_args: --as-cran

r:
  - release

r_packages:
  - pkgload
  - rsconnect

os:
  - linux
  - osx

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - devel

jobs:
  include:
    - stage: deploy
      script: Rscript -e 'covr::codecov()'
      script: if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then Rscript dev/deploy.R; fi
